# Generated by Django 4.2.2 on 2023-06-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C2BPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(max_length=15)),
                ('TransID', models.CharField(max_length=12)),
                ('TransTime', models.CharField(max_length=14)),
                ('TransAmount', models.CharField(max_length=12)),
                ('BusinessShortCode', models.CharField(blank=True, max_length=6, null=True)),
                ('BillRefNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('InvoiceNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('OrgAccountBalance', models.CharField(blank=True, max_length=12, null=True)),
                ('ThirdPartyTransID', models.CharField(blank=True, max_length=20, null=True)),
                ('MSISDN', models.CharField(blank=True, max_length=12, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=25, null=True)),
                ('MiddleName', models.CharField(blank=True, max_length=25, null=True)),
                ('LastName', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LipaNaMpesaTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(max_length=50)),
                ('CheckOutRequestID', models.CharField(max_length=50)),
                ('ResultCode', models.IntegerField()),
                ('ResultDesc', models.CharField(max_length=150)),
                ('Amount', models.FloatField()),
                ('MpesaReceiptNumber', models.TextField(max_length=15)),
                ('TransactionDate', models.DateTimeField()),
                ('PhoneNumber', models.CharField(max_length=13)),
            ],
        ),
    ]
