# Generated by Django 4.2.2 on 2023-06-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LipaNaMpesaTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(max_length=50)),
                ('CheckOutRequestID', models.CharField(max_length=50)),
                ('ResultCode', models.IntegerField()),
                ('ResultDesc', models.CharField(max_length=150)),
                ('Amount', models.FloatField()),
                ('MpesaReceiptNumber', models.TextField(max_length=15)),
                ('TransactionDate', models.DateTimeField()),
                ('PhoneNumber', models.CharField(max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='LipaNaMpesa',
        ),
    ]
